### ISSUE TITLE
First Use

### ISSUE THREAD

**Issue by UserZerro** [jamal0025/GoogleBuddy#1]
This was my first use of GoogleBuddy and overall I was extremely impressed! It literally does exactly what is claimed and searches Google in 3 seconds. 

Feedback:
- Search phrase included all 3 answers, not the indicated option only.
- Allow user to Select Incognito browser or standard
- Search in the same tab, opening a new tab with each search clutters the Chrome window with tabs and takes additional time to open.
- I needed assistance installing and setting up GoogleBuddy which means others will to. Eventually, this should be an .exe file so it can be easily utilized by more people.

**Comment by jamal0025** [comment]
Feedback reformatted via 'Feedback' link on the website. Please submit any other feedback via http://bit.ly/GoogleBuddyFeedback.
